name: freyja-sra
channels:
    - bioconda
    - conda-forge
dependencies:
  - bioconda::cutadapt=4.4
  - bioconda::freyja=1.4.7
  - bioconda::nextflow=23.04.3
  - bioconda::minimap2=2.26
  - conda-forge::awscli=2.13.34
  - conda-forge::google-cloud-sdk=458.0.1