name: Update NCBI metadata

on:
  schedule:
      - cron:  '0 0 * * *'

jobs:
  fetch_ncbi_metadata:
    runs-on: self-hosted

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Install python
        run: |
              dnf install python3 -y
              dnf install python3-pip -y

      - name: Install dependencies
        run: |
              pip install pandas biopython shortuuid

      - name: Fetch NCBI metadata
        run: python scripts/fetch_sra_metadata.py

      - name: Commit and push changes
        run: |
              git config --local user.name "$GITHUB_ACTOR"
              git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
              git add -A
              git commit -m "Update metadata"
              git push